# Site settings
title: "Sean Choe's Blog"
email: sean@seanchoe.com
description: > # this means to ignore newlines until "baseurl:"
  "Sean Choe's Blog Posts and Works"
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://seanchoe.com" # the base hostname & protocol for your site
twitter_username: seanchoe
github_username:  seanchoe
permalink:  /:year/:month/:title/

# Build settings
markdown: kramdown
