# Site settings
title: "Sean Choe : Blog"
email: sean@seanchoe.com
description: "Sean Choe is a UI/UX Designer, iOS/Web Developer and movie lover. Take a look at his thoughts on world."
baseurl: ""
url: http://blog.seanchoe.com
twitter_username: seanchoe
github_username:  seanchoe
permalink: /:year/:month/:title/
paginate: 10
paginate_path: page:num

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      author: "Sean Choe"
