# Site settings
title: "Sean Choe | Blog"
email: sean@seanchoe.com
description: "Sean Choe is a UI/UX Designer, an iOS/Web Developer and a movie lover. Take a look at his thoughts on the world."
baseurl: ""
url: https://seanchoe.com/blog
twitter_username: seanchoe
github_username:  seanchoe
permalink: /:year/:month/:title/
paginate: 5
paginate_path: page:num
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      author: "Sean Choe"
